"""
color1 = Color1()
color2 = Color2()
color3 = Color3()
color4 = Color4()
all_sprites.add(color1, color2, color3, color4)
color1a = Color1a()
color2a = Color2a()
color3a = Color3a()
color4a = Color4a()
all_sprites.add(color1a, color2a, color3a, color4a)
color1b = Color1b()
color2b = Color2b()
color3b = Color3b()
color4b = Color4b()
all_sprites.add(color1b, color2b, color3b, color4b)
color1c = Color1c()
color2c = Color2c()
color3c = Color3c()
color4c = Color4c()
all_sprites.add(color1c, color2c, color3c, color4c)
color1d = Color1d()
color2d = Color2d()
color3d = Color3d()
color4d = Color4d()
all_sprites.add(color1d, color2d, color3d, color4d)
color1e = Color1e()
color2e = Color2e()
color3e = Color3e()
color4e = Color4e()
all_sprites.add(color1e, color2e, color3e, color4e)
color1f = Color1f()
color2f = Color2f()
color3f = Color3f()
color4f = Color4f()
all_sprites.add(color1f, color2f, color3f, color4f)
color1g = Color1g()
color2g = Color2g()
color3g = Color3g()
color4g = Color4g()
all_sprites.add(color1g, color2g, color3g, color4g)
color1h = Color1h()
color2h = Color2h()
color3h = Color3h()
color4h = Color4h()
all_sprites.add(color1h, color2h, color3h, color4h)
color1i = Color1i()
color2i = Color2i()
color3i = Color3i()
color4i = Color4i()
all_sprites.add(color1i, color2i, color3i, color4i)
color1j = Color1j()
color2j = Color2j()
color3j = Color3j()
color4j = Color4j()
all_sprites.add(color1j, color2j, color3j, color4j)
color1k = Color1k()
color2k = Color2k()
color3k = Color3k()
color4k = Color4k()
all_sprites.add(color1k, color2k, color3k, color4k)
color1l = Color1l()
color2l = Color2l()
color3l = Color3l()
color4l = Color4l()
all_sprites.add(color1l, color2l, color3l, color4l)
color1m = Color1m()
color2m = Color2m()
color3m = Color3m()
color4m = Color4m()
all_sprites.add(color1m, color2m, color3m, color4m)





value1r = Value1r()
value2r = Value2r()
value3r = Value3r()
value4r = Value4r()
all_sprites.add(value1r, value2r, value3r, value4r)
value1ra = Value1ra()
value2ra = Value2ra()
value3ra = Value3ra()
value4ra = Value4ra()
all_sprites.add(value1ra, value2ra, value3ra, value4ra)
value1rb = Value1rb()
value2rb = Value2rb()
value3rb = Value3rb()
value4rb = Value4rb()
all_sprites.add(value1rb, value2rb, value3rb, value4rb)
value1rc = Value1rc()
value2rc = Value2rc()
value3rc = Value3rc()
value4rc = Value4rc()
all_sprites.add(value1rc, value2rc, value3rc, value4rc)
value1rd = Value1rd()
value2rd = Value2rd()
value3rd = Value3rd()
value4rd = Value4rd()
all_sprites.add(value1rd, value2rd, value3rd, value4rd)
value1re = Value1re()
value2re = Value2re()
value3re = Value3re()
value4re = Value4re()
all_sprites.add(value1re, value2re, value3re, value4re)
value1rf = Value1rf()
value2rf = Value2rf()
value3rf = Value3rf()
value4rf = Value4rf()
all_sprites.add(value1rf, value2rf, value3rf, value4rf)
value1rg = Value1rg()
value2rg = Value2rg()
value3rg = Value3rg()
value4rg = Value4rg()
all_sprites.add(value1rg, value2rg, value3rg, value4rg)
value1rh = Value1rh()
value2rh = Value2rh()
value3rh = Value3rh()
value4rh = Value4rh()
all_sprites.add(value1rh, value2rh, value3rh, value4rh)
value1ri = Value1ri()
value2ri = Value2ri()
value3ri = Value3ri()
value4ri = Value4ri()
all_sprites.add(value1ri, value2ri, value3ri, value4ri)
value1rj = Value1rj()
value2rj = Value2rj()
value3rj = Value3rj()
value4rj = Value4rj()
all_sprites.add(value1rj, value2rj, value3rj, value4rj)
value1rk = Value1rk()
value2rk = Value2rk()
value3rk = Value3rk()
value4rk = Value4rk()
all_sprites.add(value1rk, value2rk, value3rk, value4rk)
value1rl = Value1rl()
value2rl = Value2rl()
value3rl = Value3rl()
value4rl = Value4rl()
all_sprites.add(value1l, value2rl, value3rl, value4rl)
value1rm = Value1rm()
value2rm = Value2rm()
value3rm = Value3rm()
value4rm = Value4rm()
all_sprites.add(value1rm, value2rm, value3rm, value4rm)


value1w = Value1w()
value2w = Value2w()
value3w = Value3w()
value4w = Value4w()
all_sprites.add(value1w, value2w, value3w, value4w)
value1wa = Value1wa()
value2wa = Value2wa()
value3wa = Value3wa()
value4wa = Value4wa()
all_sprites.add(value1wa, value2wa, value3wa, value4wa)
value1wb = Value1wb()
value2wb = Value2wb()
value3wb = Value3wb()
value4wb = Value4wb()
all_sprites.add(value1wb, value2wb, value3wb, value4wb)
value1wc = Value1wc()
value2wc = Value2wc()
value3wc = Value3wc()
value4wc = Value4wc()
all_sprites.add(value1wc, value2wc, value3wc, value4wc)
value1wd = Value1wd()
value2wd = Value2wd()
value3wd = Value3wd()
value4wd = Value4wd()
all_sprites.add(value1wd, value2wd, value3wd, value4wd)
value1we = Value1we()
value2we = Value2we()
value3we = Value3we()
value4we = Value4we()
all_sprites.add(value1we, value2we, value3we, value4we)
value1wf = Value1wf()
value2wf = Value2wf()
value3wf = Value3wf()
value4wf = Value4wf()
all_sprites.add(value1wf, value2wf, value3wf, value4wf)
value1wg = Value1wg()
value2wg = Value2wg()
value3wg = Value3wg()
value4wg = Value4wg()
all_sprites.add(value1wg, value2wg, value3wg, value4wg)
value1wh = Value1wh()
value2wh = Value2wh()
value3wh = Value3wh()
value4wh = Value4wh()
all_sprites.add(value1wh, value2wh, value3wh, value4wh)
value1wi = Value1wi()
value2wi = Value2wi()
value3wi = Value3wi()
value4wi = Value4wi()
all_sprites.add(value1wi, value2wi, value3wi, value4wi)
value1wj = Value1wj()
value2wj = Value2wj()
value3wj = Value3wj()
value4wj = Value4wj()
all_sprites.add(value1wj, value2wj, value3wj, value4wj)
value1wk = Value1wk()
value2wk = Value2wk()
value3wk = Value3wk()
value4wk = Value4wk()
all_sprites.add(value1wk, value2wk, value3wk, value4wk)
value1wl = Value1wl()
value2wl = Value2wl()
value3wl = Value3wl()
value4wl = Value4wl()
all_sprites.add(value1wl, value2wl, value3wl, value4wl)
value1wm = Value1wm()
value2wm = Value2wm()
value3wm = Value3wm()
value4wm = Value4wm()
all_sprites.add(value1wm, value2wm, value3wm, value4wm)
"""